package vista;

import java.awt.event.KeyEvent;
import controlador.ControlPartido;
import controlador.Validaciones;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Partido;
import javax.swing.RowFilter;
/**
 *
 * @author TOSHIBA
 */
public class FrmPartido extends javax.swing.JInternalFrame {
    private int editar=0;//Bandera para diferenciar si el BtnGuardar hará un INSERT o un UPDATE
    private int nuevo=0;//Bandera para determinar evitar que se ingrese el mismo registro más de una vez
    TableRowSorter tbs ;
    DefaultTableModel model;
    Validaciones val = new Validaciones();
    /**
     * Creates new form frmPartido
     */
    public FrmPartido() {
        initComponents();
        mostrar();
        llenarComboTorneo();
        llenarComboEquipo();
        llenarComboEstadio();
        llenarComboArbitro();
        llenarComboJornada();
        llenarComboHorario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void insertar(){
        Partido pa = new Partido();
        ControlPartido cp = new ControlPartido();
        try{
            pa.setIdTorneo(Integer.parseInt(this.jTxtIdTorneo.getText()));
            pa.setIdEquipoLocal(Integer.parseInt(this.jTxtIdLocal.getText()));
            pa.setIdEquipoVisitante(Integer.parseInt(this.jTxtIdVisitante.getText()));
            pa.setIdEstadio(Integer.parseInt(this.jTxtIdEstadio.getText()));
            pa.setFecha(this.jTxtFecha.getText());
            pa.setIdArbitro(Integer.parseInt(this.jTxtIdArbitro.getText()));
            pa.setIdHorario(Integer.parseInt(this.jComboHorario.getSelectedItem().toString()));
            pa.setIdJornada(Integer.parseInt(this.jTxtIdJornada.getText()));
            
            String msj=cp.agregarPartido(pa);
            JOptionPane.showMessageDialog(rootPane, msj, "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            mostrar();
            limpiar();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void modificar(){
        Partido pa = new Partido();
        ControlPartido cp = new ControlPartido();
        try{
            pa.setIdPartido(Integer.parseInt(this.jTxtCodigo.getText()));
            pa.setIdTorneo(Integer.parseInt(this.jTxtIdTorneo.getText()));
            pa.setIdEquipoLocal(Integer.parseInt(this.jTxtIdLocal.getText()));
            pa.setIdEquipoVisitante(Integer.parseInt(this.jTxtIdVisitante.getText()));
            pa.setIdEstadio(Integer.parseInt(this.jTxtIdEstadio.getText()));
            pa.setFecha(this.jTxtFecha.getText());
            pa.setIdArbitro(Integer.parseInt(this.jTxtIdArbitro.getText()));
            pa.setIdHorario(Integer.parseInt(this.jComboHorario.getSelectedItem().toString()));
            pa.setIdJornada(Integer.parseInt(this.jTxtIdJornada.getText()));
            
            int SiONo=JOptionPane.showConfirmDialog(this, "Desea modificar el registro", "Modificar gol", JOptionPane.YES_NO_OPTION);
            if(SiONo==0){
                String msj=cp.modificarPartido(pa);
                JOptionPane.showMessageDialog(rootPane, msj, "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                mostrar();
                limpiar();
            }else{
                limpiar();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }    
    }
    
    public void eliminar(){
        Partido pa = new Partido();
        ControlPartido cg = new ControlPartido();
        try{
            pa.setIdPartido(Integer.parseInt(this.jTxtCodigo.getText()));
            int SiONo=JOptionPane.showConfirmDialog(this, "Desea eliminar el registro", "Eliminar gol", JOptionPane.YES_NO_OPTION);
            if(SiONo==0){
                String msj=cg.eliminarPartido(pa);
                JOptionPane.showMessageDialog(rootPane, msj, "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                mostrar();
                limpiar();
            }else{
                limpiar();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public DefaultTableModel mostrar(){
        this.jTxtIdTorneo.setVisible(false);
        this.jTxtIdLocal.setVisible(false);
        this.jTxtIdVisitante.setVisible(false);
        this.jTxtIdEstadio.setVisible(false);
        this.jTxtIdArbitro.setVisible(false);
        this.jTxtIdJornada.setVisible(false);
        String []columnas={"Código","Torneo","Local","Visitante","Estadio","Árbitro","Fecha","Horario","Día","Hora","Jornada"};
        Object[]obj=new Object[11];
        DefaultTableModel tabla = new DefaultTableModel(null,columnas);
        Partido pa = new Partido();
        ControlPartido cp = new ControlPartido();
        List ls;
        try{
            ls=cp.mostrarPartido();
            for(int i=0;i<ls.size();i++){
                pa=(Partido)ls.get(i);
                obj[0]=pa.getIdPartido();
                obj[1]=pa.getNombreTorneo();
                obj[2]=pa.getNombreEquipoLocal();
                obj[3]=pa.getNombreEquipoVisitante();
                obj[4]=pa.getEstadio();
                obj[5]=pa.getNombreArbitro();
                obj[6]=pa.getFecha();
                obj[7]=pa.getIdHorario();
                obj[8]=pa.getDia();
                obj[9]=pa.getHora();
                obj[10]=pa.getNombreJornada();
                tabla.addRow(obj);
            }
            ls=cp.mostrarPartido();
            this.jTablaPartido.setModel(tabla);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al mostrar datos" + e.toString());
        }
        return tabla;
    }
    
    public void limpiar(){
        this.jTxtCodigo.setText("");
        this.jTxtFecha.setText("");
        this.jComboTorneo.setSelectedIndex(0);
        this.jComboLocal.setSelectedIndex(0);
        this.jComboVisita.setSelectedIndex(0);
        this.jComboEstadio.setSelectedIndex(0);
        this.jComboArbitro.setSelectedIndex(0);
        this.jComboJornada.setSelectedIndex(0);
        this.jComboHorario.setSelectedIndex(0);
        this.jComboBuscar.setSelectedIndex(0);
    }
    
    public boolean habilitarInput(boolean opcion, boolean opcion2){//Habilita o deshabilita los campos del formulario
        this.jTxtFecha.setEnabled(opcion);
        this.jComboTorneo.setEnabled(opcion);
        this.jComboLocal.setEnabled(opcion);
        this.jComboVisita.setEnabled(opcion);
        this.jComboEstadio.setEnabled(opcion);
        this.jComboArbitro.setEnabled(opcion);
        this.jComboJornada.setEnabled(opcion);
        this.jComboHorario.setEnabled(opcion);
        this.jTxtBusqueda.setEnabled(opcion2);
        this.jComboBuscar.setEnabled(opcion2);
        return opcion;
    } 
    
    public void llenarComboTorneo(){
        ControlPartido cp = new ControlPartido();
        List lista;
        Object item;
          try{
            lista  = cp.llenarComboBoxTorneo();
            for (int i=0;i<lista.size();i++) {
                item= lista.get(i);
                jComboTorneo.addItem(item.toString());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al mostrar datos" + e.toString());
        }              
    }
    
    public void llenarComboEquipo(){
        ControlPartido cp = new ControlPartido();
        List lista;
        Object item;
          try{
            lista  = cp.llenarComboBoxEquipo();
            for (int i=0;i<lista.size();i++) {
                item= lista.get(i);
                jComboLocal.addItem(item.toString());
            }
            
            lista  = cp.llenarComboBoxEquipo();
            for (int i=0;i<lista.size();i++) {
                item= lista.get(i);
                jComboVisita.addItem(item.toString());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al mostrar datos" + e.toString());
        }              
    }
    
    public void llenarComboEstadio(){
        ControlPartido cp = new ControlPartido();
        List lista;
        Object item;
          try{
            lista  = cp.llenarComboBoxEstadio();
            for (int i=0;i<lista.size();i++) {
                item= lista.get(i);
                jComboEstadio.addItem(item.toString());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al mostrar datos" + e.toString());
        }              
    }
    
    public void llenarComboArbitro(){
        ControlPartido cp = new ControlPartido();
        List lista;
        Object item;
          try{
            lista  = cp.llenarComboBoxArbitro();
            for (int i=0;i<lista.size();i++) {
                item= lista.get(i);
                jComboArbitro.addItem(item.toString());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al mostrar datos" + e.toString());
        }              
    }
    
    public void llenarComboJornada(){
        ControlPartido cp = new ControlPartido();
        List lista;
        Object item;
          try{
            lista  = cp.llenarComboBoxJornada();
            for (int i=0;i<lista.size();i++) {
                item= lista.get(i);
                jComboJornada.addItem(item.toString());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al mostrar datos" + e.toString());
        }              
    }
    
    public void llenarComboHorario(){
        ControlPartido cp = new ControlPartido();
        List lista;
        Object item;
          try{
            lista  = cp.llenarComboBoxHorario();
            for (int i=0;i<lista.size();i++) {
                item= lista.get(i);
                jComboHorario.addItem(item.toString());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al mostrar datos" + e.toString());
        }              
    }
    
    public void llenarTxtIdTorneo(){
        ControlPartido cp = new ControlPartido();
        String nombreTorneo = "";
        nombreTorneo = this.jComboTorneo.getSelectedItem().toString();
        int idTorneo;
        idTorneo = cp.llenarIdTorneo(nombreTorneo);
        this.jTxtIdTorneo.setText(String.valueOf(idTorneo));
    }
    
    public void llenarTxtIdEquipoLocal(){
        ControlPartido cp = new ControlPartido();
        String nombreEquipo = "";
        nombreEquipo = this.jComboLocal.getSelectedItem().toString();
        int idEquipo;
        idEquipo = cp.llenarIdEquipo(nombreEquipo);
        this.jTxtIdLocal.setText(String.valueOf(idEquipo));
    }
    
    public void llenarTxtIdEquipoVisitante(){
        ControlPartido cp = new ControlPartido();
        String nombreEquipo = "";
        nombreEquipo = this.jComboVisita.getSelectedItem().toString();
        int idEquipo;
        idEquipo = cp.llenarIdEquipo(nombreEquipo);
        this.jTxtIdVisitante.setText(String.valueOf(idEquipo));
    }
    
    public void llenarTxtIdEstadio(){
        ControlPartido cp = new ControlPartido();
        String nombreEstadio = "";
        nombreEstadio = this.jComboEstadio.getSelectedItem().toString();
        int idEstadio;
        idEstadio = cp.llenarIdEstadio(nombreEstadio);
        this.jTxtIdEstadio.setText(String.valueOf(idEstadio));
    }
    
    public void llenarTxtIdArbitro(){
        ControlPartido cp = new ControlPartido();
        String nombreArbitro = "";
        nombreArbitro = this.jComboArbitro.getSelectedItem().toString();
        int idArbitro;
        idArbitro = cp.llenarIdArbitro(nombreArbitro);
        this.jTxtIdArbitro.setText(String.valueOf(idArbitro));
    }
    
    public void llenarTxtIdJornada(){
        ControlPartido cp = new ControlPartido();
        String nombreJornada = "";
        nombreJornada = this.jComboJornada.getSelectedItem().toString();
        int idJornada;
        idJornada = cp.llenarIdJornada(nombreJornada);
        this.jTxtIdJornada.setText(String.valueOf(idJornada));
    }
    
       
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboVisita = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboArbitro = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboLocal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboEstadio = new javax.swing.JComboBox<>();
        jTxtCodigo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablaPartido = new javax.swing.JTable();
        jComboTorneo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboJornada = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboHorario = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBuscar = new javax.swing.JComboBox<>();
        jTxtBusqueda = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnNuevo = new javax.swing.JButton();
        jTxtIdTorneo = new javax.swing.JTextField();
        jTxtIdLocal = new javax.swing.JTextField();
        jTxtIdVisitante = new javax.swing.JTextField();
        jTxtIdEstadio = new javax.swing.JTextField();
        jTxtIdArbitro = new javax.swing.JTextField();
        jTxtIdJornada = new javax.swing.JTextField();
        jTxtDia = new javax.swing.JTextField();
        jTxtHora = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtFecha = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jComboVisita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        jComboVisita.setEnabled(false);
        jComboVisita.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboVisitaItemStateChanged(evt);
            }
        });

        jLabel5.setText("Equipo Visita:");

        jLabel6.setText("Estadio:");

        jComboArbitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        jComboArbitro.setEnabled(false);
        jComboArbitro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboArbitroItemStateChanged(evt);
            }
        });

        jLabel7.setText("Arbitro: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Partido");

        jComboLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        jComboLocal.setEnabled(false);
        jComboLocal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboLocalItemStateChanged(evt);
            }
        });

        jLabel2.setText("Código:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Equipo Local: ");

        jComboEstadio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        jComboEstadio.setEnabled(false);
        jComboEstadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboEstadioItemStateChanged(evt);
            }
        });

        jTxtCodigo.setEnabled(false);
        jTxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCodigoKeyTyped(evt);
            }
        });

        jTablaPartido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Torneo", "Eq.Local", "Eq.Visita", "Estadio", "Arbitro", "Fecha", "Dia", "Hora", "Jornada"
            }
        ));
        jTablaPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaPartidoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablaPartido);

        jComboTorneo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        jComboTorneo.setEnabled(false);
        jComboTorneo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboTorneoItemStateChanged(evt);
            }
        });

        jLabel8.setText("Torneo:");

        jLabel9.setText("Jornada:");

        jComboJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        jComboJornada.setEnabled(false);
        jComboJornada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboJornadaItemStateChanged(evt);
            }
        });

        jLabel10.setText("Horario:");

        jComboHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        jComboHorario.setEnabled(false);
        jComboHorario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboHorarioItemStateChanged(evt);
            }
        });

        jLabel11.setText("Busqueda:");

        jComboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno", "Código", "Torneo", "Local", "Visitante", "Estadio", "Árbitro", "Fecha", "Día", "Hora", "Jornada" }));
        jComboBuscar.setEnabled(false);

        jTxtBusqueda.setEnabled(false);
        jTxtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtBusquedaKeyTyped(evt);
            }
        });

        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBuscarMouseClicked(evt);
            }
        });

        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditarMouseClicked(evt);
            }
        });

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGuardarMouseClicked(evt);
            }
        });

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseClicked(evt);
            }
        });

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
        });

        BtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        BtnNuevo.setText("Nuevo");
        BtnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNuevoMouseClicked(evt);
            }
        });

        jTxtDia.setEnabled(false);

        jTxtHora.setEnabled(false);

        jLabel12.setText("Detalles:");

        try {
            jTxtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTxtFecha.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtHora))
                            .addComponent(jComboJornada, 0, 219, Short.MAX_VALUE)
                            .addComponent(jComboArbitro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboEstadio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboVisita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboLocal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboTorneo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtCodigo)
                            .addComponent(jComboHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtIdTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxtBusqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnBuscar)
                            .addComponent(BtnNuevo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEditar)
                            .addComponent(BtnEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnGuardar)
                            .addComponent(BtnCancelar))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jTxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTxtIdTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtIdLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTxtIdArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtIdVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTxtIdEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTxtIdJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodigoKeyTyped
        //Validación números jTxtCodigo
        val.validarNumero(evt);
    }//GEN-LAST:event_jTxtCodigoKeyTyped

    private void jTxtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBusquedaKeyTyped
        if(jComboBuscar.getSelectedItem().equals("Seleccione uno")){
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un criterio de busqueda", "Advertencia", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }else{
            this.jTxtBusqueda.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    if (jComboBuscar.getSelectedItem().equals("Código")){
                        tbs.setRowFilter(RowFilter.regexFilter("(?i)"+jTxtBusqueda.getText(), 0));
                    }else if (jComboBuscar.getSelectedItem().equals("Torneo")){
                        tbs.setRowFilter(RowFilter.regexFilter("(?i)"+jTxtBusqueda.getText(), 1));
                    }else if (jComboBuscar.getSelectedItem().equals("Local")){
                        tbs.setRowFilter(RowFilter.regexFilter("(?i)"+jTxtBusqueda.getText(), 2));
                    }else if (jComboBuscar.getSelectedItem().equals("Visitante")){
                        tbs.setRowFilter(RowFilter.regexFilter("(?i)"+jTxtBusqueda.getText(), 3));
                    }else if (jComboBuscar.getSelectedItem().equals("Estadio")){
                        tbs.setRowFilter(RowFilter.regexFilter("(?i)"+jTxtBusqueda.getText(), 4));
                    }else if (jComboBuscar.getSelectedItem().equals("Árbitro")){
                        tbs.setRowFilter(RowFilter.regexFilter("(?i)"+jTxtBusqueda.getText(), 5));
                    }else if (jComboBuscar.getSelectedItem().equals("Fecha")){
                        tbs.setRowFilter(RowFilter.regexFilter("(?i)"+jTxtBusqueda.getText(), 6));
                    }else if (jComboBuscar.getSelectedItem().equals("Día")){
                        tbs.setRowFilter(RowFilter.regexFilter("(?i)"+jTxtBusqueda.getText(), 7));
                    }else if (jComboBuscar.getSelectedItem().equals("Hora")){
                        tbs.setRowFilter(RowFilter.regexFilter("(?i)"+jTxtBusqueda.getText(), 8));
                    }else if (jComboBuscar.getSelectedItem().equals("Jornada")){
                        tbs.setRowFilter(RowFilter.regexFilter("(?i)"+jTxtBusqueda.getText(), 9));
                    }
                }
            });
        }
        DefaultTableModel tablas = mostrar();
        tbs = new TableRowSorter(tablas);
        this.jTablaPartido.setRowSorter(tbs);
    }//GEN-LAST:event_jTxtBusquedaKeyTyped

    private void BtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarMouseClicked
        habilitarInput(false,true);
    }//GEN-LAST:event_BtnBuscarMouseClicked

    private void BtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarMouseClicked
        if(this.jTxtCodigo.getText().equals("")&&this.jTxtFecha.getText().equals("")&&this.jComboTorneo.getSelectedItem().toString().equals("Seleccione uno")&&
            this.jComboLocal.getSelectedItem().toString().equals("Seleccione uno")&&this.jComboVisita.getSelectedItem().toString().equals("Seleccione uno")&&
            this.jComboEstadio.getSelectedItem().toString().equals("Seleccione uno")&&this.jComboArbitro.getSelectedItem().toString().equals("Seleccione uno")&&
            this.jComboHorario.getSelectedItem().toString().equals("Seleccione uno")&&this.jComboJornada.getSelectedItem().toString().equals("Seleccione uno")){//No permite editar sin haber seleccionado un registro
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un registro a editar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            habilitarInput(true,false);
            editar=1;
        }
    }//GEN-LAST:event_BtnEditarMouseClicked

    private void BtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardarMouseClicked
        if(nuevo==1 && this.jTxtFecha.getText().equals("")&&this.jComboTorneo.getSelectedItem().toString().equals("Seleccione uno")&&
            this.jComboLocal.getSelectedItem().toString().equals("Seleccione uno")&&this.jComboVisita.getSelectedItem().toString().equals("Seleccione uno")&&
            this.jComboEstadio.getSelectedItem().toString().equals("Seleccione uno")&&this.jComboArbitro.getSelectedItem().toString().equals("Seleccione uno")&&
            this.jComboHorario.getSelectedItem().toString().equals("Seleccione uno")&&this.jComboJornada.getSelectedItem().toString().equals("Seleccione uno")){//No permite guardar si el campo está vacío
            JOptionPane.showMessageDialog(rootPane, "Complete los campos requeridos", "ERROR", JOptionPane.ERROR_MESSAGE);
            habilitarInput(true,false);
        }else{
            if(editar==0 && nuevo==1){
                insertar();
                habilitarInput(false,false);
            }else if(editar==1){
                modificar();
                habilitarInput(false,false);
            }else if(nuevo==0 && this.jTxtFecha.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Clic en NUEVO para ingresar un gol", "ERROR", JOptionPane.ERROR_MESSAGE);
            }else if(editar==0 && nuevo==0){
                JOptionPane.showMessageDialog(rootPane, "Clic en EDITAR para guardar los cambios ó en NUEVO para crear un nuevo registro", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnGuardarMouseClicked

    private void BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseClicked
        if(this.jTxtFecha.getText().equals("")){//No permite eliminar sin haber seleccionado un registro
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un registro a eliminar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            eliminar();
        }
    }//GEN-LAST:event_BtnEliminarMouseClicked

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        habilitarInput(false,true);
        limpiar();
        nuevo=0;
    }//GEN-LAST:event_BtnCancelarMouseClicked

    private void BtnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNuevoMouseClicked
        habilitarInput(true,false);
        limpiar();
        nuevo=1;
    }//GEN-LAST:event_BtnNuevoMouseClicked

    private void jComboTorneoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboTorneoItemStateChanged
        llenarTxtIdTorneo();
    }//GEN-LAST:event_jComboTorneoItemStateChanged

    private void jComboLocalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboLocalItemStateChanged
        llenarTxtIdEquipoLocal();
    }//GEN-LAST:event_jComboLocalItemStateChanged

    private void jComboVisitaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboVisitaItemStateChanged
        llenarTxtIdEquipoVisitante();
    }//GEN-LAST:event_jComboVisitaItemStateChanged

    private void jComboEstadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboEstadioItemStateChanged
        llenarTxtIdEstadio();
    }//GEN-LAST:event_jComboEstadioItemStateChanged

    private void jComboArbitroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboArbitroItemStateChanged
        llenarTxtIdArbitro();
    }//GEN-LAST:event_jComboArbitroItemStateChanged

    private void jComboJornadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboJornadaItemStateChanged
        llenarTxtIdJornada();
    }//GEN-LAST:event_jComboJornadaItemStateChanged

    private void jComboHorarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboHorarioItemStateChanged
        
    }//GEN-LAST:event_jComboHorarioItemStateChanged

    private void jTablaPartidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaPartidoMouseClicked
        int fila=this.jTablaPartido.getSelectedRow();
        this.jTxtCodigo.setText(String.valueOf(this.jTablaPartido.getValueAt(fila, 0)));
        this.jComboTorneo.setSelectedItem(String.valueOf(this.jTablaPartido.getValueAt(fila, 1).toString()));
        this.jComboLocal.setSelectedItem(String.valueOf(this.jTablaPartido.getValueAt(fila, 2).toString()));
        this.jComboVisita.setSelectedItem(String.valueOf(this.jTablaPartido.getValueAt(fila, 3).toString()));
        this.jComboEstadio.setSelectedItem(String.valueOf(this.jTablaPartido.getValueAt(fila, 4).toString()));
        this.jComboArbitro.setSelectedItem(String.valueOf(this.jTablaPartido.getValueAt(fila, 5).toString()));
        this.jTxtFecha.setText(String.valueOf(this.jTablaPartido.getValueAt(fila, 6)));
        this.jComboHorario.setSelectedItem(String.valueOf(this.jTablaPartido.getValueAt(fila,7)));
        this.jTxtDia.setText(String.valueOf(this.jTablaPartido.getValueAt(fila, 8)));
        this.jTxtHora.setText(String.valueOf(this.jTablaPartido.getValueAt(fila, 9)));
        this.jComboJornada.setSelectedItem(String.valueOf(this.jTablaPartido.getValueAt(fila, 10).toString()));
    }//GEN-LAST:event_jTablaPartidoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JComboBox<String> jComboArbitro;
    private javax.swing.JComboBox<String> jComboBuscar;
    private javax.swing.JComboBox<String> jComboEstadio;
    private javax.swing.JComboBox<String> jComboHorario;
    private javax.swing.JComboBox<String> jComboJornada;
    private javax.swing.JComboBox<String> jComboLocal;
    private javax.swing.JComboBox<String> jComboTorneo;
    private javax.swing.JComboBox<String> jComboVisita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablaPartido;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTxtBusqueda;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtDia;
    private javax.swing.JFormattedTextField jTxtFecha;
    private javax.swing.JTextField jTxtHora;
    private javax.swing.JTextField jTxtIdArbitro;
    private javax.swing.JTextField jTxtIdEstadio;
    private javax.swing.JTextField jTxtIdJornada;
    private javax.swing.JTextField jTxtIdLocal;
    private javax.swing.JTextField jTxtIdTorneo;
    private javax.swing.JTextField jTxtIdVisitante;
    // End of variables declaration//GEN-END:variables
}
